function homePosition() {
    pins.servoWritePin(AnalogPin.P0, 60)
    basic.pause(500)
    pins.servoWritePin(AnalogPin.P1, 123)
    pins.servoWritePin(AnalogPin.P2, 57)
    basic.pause(1000)
}
function clearBoard() {
    pins.servoWritePin(AnalogPin.P0, 60)
    basic.pause(200)

    pins.servoWritePin(AnalogPin.P1, 55)
    pins.servoWritePin(AnalogPin.P2, 39)
    basic.pause(500)
    pins.servoWritePin(AnalogPin.P0, 105)
    basic.pause(200)
    pins.servoWritePin(AnalogPin.P1, 55)
    pins.servoWritePin(AnalogPin.P2, 39)
    basic.pause(20)
    pins.servoWritePin(AnalogPin.P1, 57)
    pins.servoWritePin(AnalogPin.P2, 40)
    basic.pause(20)
    pins.servoWritePin(AnalogPin.P1, 60)
    pins.servoWritePin(AnalogPin.P2, 40)
    basic.pause(20)
    pins.servoWritePin(AnalogPin.P1, 63)
    pins.servoWritePin(AnalogPin.P2, 41)
    basic.pause(20)
    pins.servoWritePin(AnalogPin.P1, 66)
    pins.servoWritePin(AnalogPin.P2, 42)
    basic.pause(20)
    pins.servoWritePin(AnalogPin.P1, 69)
    pins.servoWritePin(AnalogPin.P2, 43)
    basic.pause(20)
    pins.servoWritePin(AnalogPin.P1, 73)
    pins.servoWritePin(AnalogPin.P2, 45)
    basic.pause(20)
    pins.servoWritePin(AnalogPin.P1, 76)
    pins.servoWritePin(AnalogPin.P2, 47)
    basic.pause(20)
    pins.servoWritePin(AnalogPin.P1, 80)
    pins.servoWritePin(AnalogPin.P2, 49)
    basic.pause(20)
    pins.servoWritePin(AnalogPin.P1, 83)
    pins.servoWritePin(AnalogPin.P2, 51)
    basic.pause(20)
    pins.servoWritePin(AnalogPin.P1, 87)
    pins.servoWritePin(AnalogPin.P2, 53)
    basic.pause(20)
    pins.servoWritePin(AnalogPin.P1, 91)
    pins.servoWritePin(AnalogPin.P2, 56)
    basic.pause(20)
    pins.servoWritePin(AnalogPin.P1, 96)
    pins.servoWritePin(AnalogPin.P2, 59)
    basic.pause(20)
    pins.servoWritePin(AnalogPin.P1, 100)
    pins.servoWritePin(AnalogPin.P2, 63)
    basic.pause(20)
    pins.servoWritePin(AnalogPin.P1, 105)
    pins.servoWritePin(AnalogPin.P2, 67)
    basic.pause(20)
    pins.servoWritePin(AnalogPin.P1, 109)
    pins.servoWritePin(AnalogPin.P2, 71)
    basic.pause(20)
    pins.servoWritePin(AnalogPin.P1, 114)
    pins.servoWritePin(AnalogPin.P2, 75)
    basic.pause(20)
    pins.servoWritePin(AnalogPin.P1, 118)
    pins.servoWritePin(AnalogPin.P2, 80)
    basic.pause(20)
    pins.servoWritePin(AnalogPin.P1, 122)
    pins.servoWritePin(AnalogPin.P2, 84)
    basic.pause(20)
    pins.servoWritePin(AnalogPin.P1, 126)
    pins.servoWritePin(AnalogPin.P2, 89)
    basic.pause(20)
    pins.servoWritePin(AnalogPin.P1, 130)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(20)
    pins.servoWritePin(AnalogPin.P1, 134)
    pins.servoWritePin(AnalogPin.P2, 97)
    basic.pause(20)
    pins.servoWritePin(AnalogPin.P1, 137)
    pins.servoWritePin(AnalogPin.P2, 102)
    basic.pause(20)
    pins.servoWritePin(AnalogPin.P1, 140)
    pins.servoWritePin(AnalogPin.P2, 106)
    basic.pause(20)
    pins.servoWritePin(AnalogPin.P1, 143)
    pins.servoWritePin(AnalogPin.P2, 110)
    basic.pause(20)
    pins.servoWritePin(AnalogPin.P1, 145)
    pins.servoWritePin(AnalogPin.P2, 114)
    basic.pause(20)
    pins.servoWritePin(AnalogPin.P0, 60)
    basic.pause(200)

    pins.servoWritePin(AnalogPin.P1, 149)
    pins.servoWritePin(AnalogPin.P2, 121)
    basic.pause(500)
    pins.servoWritePin(AnalogPin.P0, 105)
    basic.pause(200)
    pins.servoWritePin(AnalogPin.P1, 149)
    pins.servoWritePin(AnalogPin.P2, 121)
    basic.pause(20)
    pins.servoWritePin(AnalogPin.P1, 147)
    pins.servoWritePin(AnalogPin.P2, 117)
    basic.pause(20)
    pins.servoWritePin(AnalogPin.P1, 145)
    pins.servoWritePin(AnalogPin.P2, 114)
    basic.pause(20)
    pins.servoWritePin(AnalogPin.P1, 143)
    pins.servoWritePin(AnalogPin.P2, 110)
    basic.pause(20)
    pins.servoWritePin(AnalogPin.P1, 140)
    pins.servoWritePin(AnalogPin.P2, 106)
    basic.pause(20)
    pins.servoWritePin(AnalogPin.P1, 137)
    pins.servoWritePin(AnalogPin.P2, 102)
    basic.pause(20)
    pins.servoWritePin(AnalogPin.P1, 134)
    pins.servoWritePin(AnalogPin.P2, 97)
    basic.pause(20)
    pins.servoWritePin(AnalogPin.P1, 130)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(20)
    pins.servoWritePin(AnalogPin.P1, 126)
    pins.servoWritePin(AnalogPin.P2, 89)
    basic.pause(20)
    pins.servoWritePin(AnalogPin.P1, 122)
    pins.servoWritePin(AnalogPin.P2, 84)
    basic.pause(20)
    pins.servoWritePin(AnalogPin.P1, 118)
    pins.servoWritePin(AnalogPin.P2, 80)
    basic.pause(20)
    pins.servoWritePin(AnalogPin.P1, 114)
    pins.servoWritePin(AnalogPin.P2, 75)
    basic.pause(20)
    pins.servoWritePin(AnalogPin.P1, 109)
    pins.servoWritePin(AnalogPin.P2, 71)
    basic.pause(20)
    pins.servoWritePin(AnalogPin.P1, 105)
    pins.servoWritePin(AnalogPin.P2, 67)
    basic.pause(20)
    pins.servoWritePin(AnalogPin.P1, 100)
    pins.servoWritePin(AnalogPin.P2, 63)
    basic.pause(20)
    pins.servoWritePin(AnalogPin.P1, 96)
    pins.servoWritePin(AnalogPin.P2, 59)
    basic.pause(20)
    pins.servoWritePin(AnalogPin.P1, 91)
    pins.servoWritePin(AnalogPin.P2, 56)
    basic.pause(20)
    pins.servoWritePin(AnalogPin.P1, 87)
    pins.servoWritePin(AnalogPin.P2, 53)
    basic.pause(20)
    pins.servoWritePin(AnalogPin.P1, 83)
    pins.servoWritePin(AnalogPin.P2, 51)
    basic.pause(20)
    pins.servoWritePin(AnalogPin.P1, 80)
    pins.servoWritePin(AnalogPin.P2, 49)
    basic.pause(20)
    pins.servoWritePin(AnalogPin.P1, 76)
    pins.servoWritePin(AnalogPin.P2, 47)
    basic.pause(20)
    pins.servoWritePin(AnalogPin.P1, 73)
    pins.servoWritePin(AnalogPin.P2, 45)
    basic.pause(20)
    pins.servoWritePin(AnalogPin.P1, 69)
    pins.servoWritePin(AnalogPin.P2, 43)
    basic.pause(20)
    pins.servoWritePin(AnalogPin.P1, 66)
    pins.servoWritePin(AnalogPin.P2, 42)
    basic.pause(20)
    pins.servoWritePin(AnalogPin.P1, 63)
    pins.servoWritePin(AnalogPin.P2, 41)
    basic.pause(20)
    pins.servoWritePin(AnalogPin.P1, 60)
    pins.servoWritePin(AnalogPin.P2, 40)
    basic.pause(20)
    pins.servoWritePin(AnalogPin.P0, 60)
    basic.pause(200)
}
function drawR() {
    pins.servoWritePin(AnalogPin.P0, 60)
    basic.pause(200)

    pins.servoWritePin(AnalogPin.P1, 78)
    pins.servoWritePin(AnalogPin.P2, 106)
    basic.pause(500)
    pins.servoWritePin(AnalogPin.P0, 80)
    basic.pause(200)
    pins.servoWritePin(AnalogPin.P1, 78)
    pins.servoWritePin(AnalogPin.P2, 106)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 78)
    pins.servoWritePin(AnalogPin.P2, 105)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 78)
    pins.servoWritePin(AnalogPin.P2, 105)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 78)
    pins.servoWritePin(AnalogPin.P2, 105)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 78)
    pins.servoWritePin(AnalogPin.P2, 105)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 78)
    pins.servoWritePin(AnalogPin.P2, 104)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 78)
    pins.servoWritePin(AnalogPin.P2, 104)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 78)
    pins.servoWritePin(AnalogPin.P2, 104)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 78)
    pins.servoWritePin(AnalogPin.P2, 104)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 78)
    pins.servoWritePin(AnalogPin.P2, 104)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 79)
    pins.servoWritePin(AnalogPin.P2, 104)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 79)
    pins.servoWritePin(AnalogPin.P2, 104)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 79)
    pins.servoWritePin(AnalogPin.P2, 104)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 79)
    pins.servoWritePin(AnalogPin.P2, 104)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 79)
    pins.servoWritePin(AnalogPin.P2, 104)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 79)
    pins.servoWritePin(AnalogPin.P2, 104)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 79)
    pins.servoWritePin(AnalogPin.P2, 104)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 80)
    pins.servoWritePin(AnalogPin.P2, 104)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 80)
    pins.servoWritePin(AnalogPin.P2, 104)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 80)
    pins.servoWritePin(AnalogPin.P2, 104)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 80)
    pins.servoWritePin(AnalogPin.P2, 104)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 80)
    pins.servoWritePin(AnalogPin.P2, 104)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 80)
    pins.servoWritePin(AnalogPin.P2, 104)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 81)
    pins.servoWritePin(AnalogPin.P2, 104)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 81)
    pins.servoWritePin(AnalogPin.P2, 104)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 81)
    pins.servoWritePin(AnalogPin.P2, 104)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 81)
    pins.servoWritePin(AnalogPin.P2, 104)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 81)
    pins.servoWritePin(AnalogPin.P2, 104)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 82)
    pins.servoWritePin(AnalogPin.P2, 104)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 82)
    pins.servoWritePin(AnalogPin.P2, 104)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 82)
    pins.servoWritePin(AnalogPin.P2, 104)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 82)
    pins.servoWritePin(AnalogPin.P2, 104)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 82)
    pins.servoWritePin(AnalogPin.P2, 104)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 83)
    pins.servoWritePin(AnalogPin.P2, 104)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 83)
    pins.servoWritePin(AnalogPin.P2, 104)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 83)
    pins.servoWritePin(AnalogPin.P2, 104)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 83)
    pins.servoWritePin(AnalogPin.P2, 104)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 83)
    pins.servoWritePin(AnalogPin.P2, 104)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 83)
    pins.servoWritePin(AnalogPin.P2, 104)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 84)
    pins.servoWritePin(AnalogPin.P2, 104)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 84)
    pins.servoWritePin(AnalogPin.P2, 104)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 84)
    pins.servoWritePin(AnalogPin.P2, 104)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 84)
    pins.servoWritePin(AnalogPin.P2, 104)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 84)
    pins.servoWritePin(AnalogPin.P2, 104)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 85)
    pins.servoWritePin(AnalogPin.P2, 104)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 85)
    pins.servoWritePin(AnalogPin.P2, 105)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 85)
    pins.servoWritePin(AnalogPin.P2, 105)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 85)
    pins.servoWritePin(AnalogPin.P2, 105)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 85)
    pins.servoWritePin(AnalogPin.P2, 105)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 86)
    pins.servoWritePin(AnalogPin.P2, 105)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 86)
    pins.servoWritePin(AnalogPin.P2, 105)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 86)
    pins.servoWritePin(AnalogPin.P2, 105)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 86)
    pins.servoWritePin(AnalogPin.P2, 105)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 87)
    pins.servoWritePin(AnalogPin.P2, 105)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 87)
    pins.servoWritePin(AnalogPin.P2, 105)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 87)
    pins.servoWritePin(AnalogPin.P2, 105)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 87)
    pins.servoWritePin(AnalogPin.P2, 105)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 87)
    pins.servoWritePin(AnalogPin.P2, 105)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 88)
    pins.servoWritePin(AnalogPin.P2, 106)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 88)
    pins.servoWritePin(AnalogPin.P2, 106)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 88)
    pins.servoWritePin(AnalogPin.P2, 106)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 88)
    pins.servoWritePin(AnalogPin.P2, 106)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 89)
    pins.servoWritePin(AnalogPin.P2, 106)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 89)
    pins.servoWritePin(AnalogPin.P2, 106)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 89)
    pins.servoWritePin(AnalogPin.P2, 106)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 89)
    pins.servoWritePin(AnalogPin.P2, 106)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 90)
    pins.servoWritePin(AnalogPin.P2, 106)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 90)
    pins.servoWritePin(AnalogPin.P2, 107)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 90)
    pins.servoWritePin(AnalogPin.P2, 107)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 90)
    pins.servoWritePin(AnalogPin.P2, 107)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 91)
    pins.servoWritePin(AnalogPin.P2, 107)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 91)
    pins.servoWritePin(AnalogPin.P2, 107)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 91)
    pins.servoWritePin(AnalogPin.P2, 107)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 91)
    pins.servoWritePin(AnalogPin.P2, 107)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 91)
    pins.servoWritePin(AnalogPin.P2, 108)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 92)
    pins.servoWritePin(AnalogPin.P2, 108)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 92)
    pins.servoWritePin(AnalogPin.P2, 108)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 92)
    pins.servoWritePin(AnalogPin.P2, 108)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 92)
    pins.servoWritePin(AnalogPin.P2, 108)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 93)
    pins.servoWritePin(AnalogPin.P2, 108)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 93)
    pins.servoWritePin(AnalogPin.P2, 108)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 93)
    pins.servoWritePin(AnalogPin.P2, 108)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 93)
    pins.servoWritePin(AnalogPin.P2, 109)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 94)
    pins.servoWritePin(AnalogPin.P2, 109)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 94)
    pins.servoWritePin(AnalogPin.P2, 109)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P0, 60)
    basic.pause(200)
    pins.servoWritePin(AnalogPin.P1, 78)
    pins.servoWritePin(AnalogPin.P2, 103)
    basic.pause(500)
    pins.servoWritePin(AnalogPin.P0, 80)
    basic.pause(200)
    pins.servoWritePin(AnalogPin.P1, 78)
    pins.servoWritePin(AnalogPin.P2, 103)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 78)
    pins.servoWritePin(AnalogPin.P2, 103)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 78)
    pins.servoWritePin(AnalogPin.P2, 103)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 78)
    pins.servoWritePin(AnalogPin.P2, 102)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 78)
    pins.servoWritePin(AnalogPin.P2, 102)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 78)
    pins.servoWritePin(AnalogPin.P2, 102)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 78)
    pins.servoWritePin(AnalogPin.P2, 101)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 78)
    pins.servoWritePin(AnalogPin.P2, 101)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 78)
    pins.servoWritePin(AnalogPin.P2, 101)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 78)
    pins.servoWritePin(AnalogPin.P2, 101)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 78)
    pins.servoWritePin(AnalogPin.P2, 101)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 78)
    pins.servoWritePin(AnalogPin.P2, 101)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 78)
    pins.servoWritePin(AnalogPin.P2, 100)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 78)
    pins.servoWritePin(AnalogPin.P2, 100)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 78)
    pins.servoWritePin(AnalogPin.P2, 100)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 77)
    pins.servoWritePin(AnalogPin.P2, 100)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 77)
    pins.servoWritePin(AnalogPin.P2, 100)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 77)
    pins.servoWritePin(AnalogPin.P2, 99)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 77)
    pins.servoWritePin(AnalogPin.P2, 99)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 77)
    pins.servoWritePin(AnalogPin.P2, 99)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 77)
    pins.servoWritePin(AnalogPin.P2, 99)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 77)
    pins.servoWritePin(AnalogPin.P2, 99)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 77)
    pins.servoWritePin(AnalogPin.P2, 98)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 77)
    pins.servoWritePin(AnalogPin.P2, 98)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 77)
    pins.servoWritePin(AnalogPin.P2, 98)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 77)
    pins.servoWritePin(AnalogPin.P2, 98)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 77)
    pins.servoWritePin(AnalogPin.P2, 97)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 77)
    pins.servoWritePin(AnalogPin.P2, 97)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 77)
    pins.servoWritePin(AnalogPin.P2, 97)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 76)
    pins.servoWritePin(AnalogPin.P2, 97)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 76)
    pins.servoWritePin(AnalogPin.P2, 96)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 76)
    pins.servoWritePin(AnalogPin.P2, 96)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 76)
    pins.servoWritePin(AnalogPin.P2, 96)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 76)
    pins.servoWritePin(AnalogPin.P2, 96)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 76)
    pins.servoWritePin(AnalogPin.P2, 96)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 76)
    pins.servoWritePin(AnalogPin.P2, 96)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 76)
    pins.servoWritePin(AnalogPin.P2, 96)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 76)
    pins.servoWritePin(AnalogPin.P2, 95)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 76)
    pins.servoWritePin(AnalogPin.P2, 95)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 76)
    pins.servoWritePin(AnalogPin.P2, 95)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 76)
    pins.servoWritePin(AnalogPin.P2, 94)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 76)
    pins.servoWritePin(AnalogPin.P2, 94)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 76)
    pins.servoWritePin(AnalogPin.P2, 94)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 76)
    pins.servoWritePin(AnalogPin.P2, 94)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 76)
    pins.servoWritePin(AnalogPin.P2, 94)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 76)
    pins.servoWritePin(AnalogPin.P2, 94)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 76)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 76)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 76)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 76)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 75)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 75)
    pins.servoWritePin(AnalogPin.P2, 92)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 75)
    pins.servoWritePin(AnalogPin.P2, 92)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 75)
    pins.servoWritePin(AnalogPin.P2, 92)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 75)
    pins.servoWritePin(AnalogPin.P2, 92)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 75)
    pins.servoWritePin(AnalogPin.P2, 91)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 75)
    pins.servoWritePin(AnalogPin.P2, 91)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 75)
    pins.servoWritePin(AnalogPin.P2, 91)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 75)
    pins.servoWritePin(AnalogPin.P2, 91)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 74)
    pins.servoWritePin(AnalogPin.P2, 90)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 74)
    pins.servoWritePin(AnalogPin.P2, 90)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 74)
    pins.servoWritePin(AnalogPin.P2, 90)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 74)
    pins.servoWritePin(AnalogPin.P2, 90)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 74)
    pins.servoWritePin(AnalogPin.P2, 89)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 74)
    pins.servoWritePin(AnalogPin.P2, 89)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 74)
    pins.servoWritePin(AnalogPin.P2, 89)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 74)
    pins.servoWritePin(AnalogPin.P2, 89)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 73)
    pins.servoWritePin(AnalogPin.P2, 88)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 73)
    pins.servoWritePin(AnalogPin.P2, 88)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 73)
    pins.servoWritePin(AnalogPin.P2, 88)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 73)
    pins.servoWritePin(AnalogPin.P2, 88)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 73)
    pins.servoWritePin(AnalogPin.P2, 88)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 73)
    pins.servoWritePin(AnalogPin.P2, 87)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 72)
    pins.servoWritePin(AnalogPin.P2, 87)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 72)
    pins.servoWritePin(AnalogPin.P2, 87)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 72)
    pins.servoWritePin(AnalogPin.P2, 87)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 72)
    pins.servoWritePin(AnalogPin.P2, 87)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 72)
    pins.servoWritePin(AnalogPin.P2, 87)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 72)
    pins.servoWritePin(AnalogPin.P2, 86)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 71)
    pins.servoWritePin(AnalogPin.P2, 86)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 71)
    pins.servoWritePin(AnalogPin.P2, 86)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 71)
    pins.servoWritePin(AnalogPin.P2, 86)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 71)
    pins.servoWritePin(AnalogPin.P2, 86)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 70)
    pins.servoWritePin(AnalogPin.P2, 86)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 70)
    pins.servoWritePin(AnalogPin.P2, 86)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 70)
    pins.servoWritePin(AnalogPin.P2, 85)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 70)
    pins.servoWritePin(AnalogPin.P2, 85)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 70)
    pins.servoWritePin(AnalogPin.P2, 85)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 69)
    pins.servoWritePin(AnalogPin.P2, 85)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 69)
    pins.servoWritePin(AnalogPin.P2, 85)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 69)
    pins.servoWritePin(AnalogPin.P2, 85)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 69)
    pins.servoWritePin(AnalogPin.P2, 85)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 69)
    pins.servoWritePin(AnalogPin.P2, 84)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 68)
    pins.servoWritePin(AnalogPin.P2, 84)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 68)
    pins.servoWritePin(AnalogPin.P2, 84)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 68)
    pins.servoWritePin(AnalogPin.P2, 84)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 68)
    pins.servoWritePin(AnalogPin.P2, 84)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P0, 60)
    basic.pause(200)
}
function drawE() {
    pins.servoWritePin(AnalogPin.P1, 83)
    pins.servoWritePin(AnalogPin.P2, 103)
    basic.pause(500)
    pins.servoWritePin(AnalogPin.P0, 80)
    basic.pause(200)
    pins.servoWritePin(AnalogPin.P1, 83)
    pins.servoWritePin(AnalogPin.P2, 103)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 83)
    pins.servoWritePin(AnalogPin.P2, 102)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 83)
    pins.servoWritePin(AnalogPin.P2, 102)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 83)
    pins.servoWritePin(AnalogPin.P2, 102)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 83)
    pins.servoWritePin(AnalogPin.P2, 102)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 82)
    pins.servoWritePin(AnalogPin.P2, 101)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 82)
    pins.servoWritePin(AnalogPin.P2, 101)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 82)
    pins.servoWritePin(AnalogPin.P2, 101)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 82)
    pins.servoWritePin(AnalogPin.P2, 101)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 82)
    pins.servoWritePin(AnalogPin.P2, 100)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 82)
    pins.servoWritePin(AnalogPin.P2, 100)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 82)
    pins.servoWritePin(AnalogPin.P2, 100)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 82)
    pins.servoWritePin(AnalogPin.P2, 100)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 81)
    pins.servoWritePin(AnalogPin.P2, 100)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 81)
    pins.servoWritePin(AnalogPin.P2, 99)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 81)
    pins.servoWritePin(AnalogPin.P2, 99)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 81)
    pins.servoWritePin(AnalogPin.P2, 99)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 81)
    pins.servoWritePin(AnalogPin.P2, 99)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 81)
    pins.servoWritePin(AnalogPin.P2, 99)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 81)
    pins.servoWritePin(AnalogPin.P2, 98)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 81)
    pins.servoWritePin(AnalogPin.P2, 98)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P0, 60)
    basic.pause(200)
    pins.servoWritePin(AnalogPin.P1, 89)
    pins.servoWritePin(AnalogPin.P2, 103)
    basic.pause(500)
    pins.servoWritePin(AnalogPin.P0, 80)
    basic.pause(200)
    pins.servoWritePin(AnalogPin.P1, 89)
    pins.servoWritePin(AnalogPin.P2, 103)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 89)
    pins.servoWritePin(AnalogPin.P2, 103)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 88)
    pins.servoWritePin(AnalogPin.P2, 102)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 88)
    pins.servoWritePin(AnalogPin.P2, 102)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 88)
    pins.servoWritePin(AnalogPin.P2, 102)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 88)
    pins.servoWritePin(AnalogPin.P2, 102)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 88)
    pins.servoWritePin(AnalogPin.P2, 101)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 88)
    pins.servoWritePin(AnalogPin.P2, 101)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 88)
    pins.servoWritePin(AnalogPin.P2, 101)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 88)
    pins.servoWritePin(AnalogPin.P2, 101)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 87)
    pins.servoWritePin(AnalogPin.P2, 101)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 87)
    pins.servoWritePin(AnalogPin.P2, 100)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 87)
    pins.servoWritePin(AnalogPin.P2, 100)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 87)
    pins.servoWritePin(AnalogPin.P2, 100)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 87)
    pins.servoWritePin(AnalogPin.P2, 100)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 86)
    pins.servoWritePin(AnalogPin.P2, 100)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 86)
    pins.servoWritePin(AnalogPin.P2, 100)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 86)
    pins.servoWritePin(AnalogPin.P2, 99)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 86)
    pins.servoWritePin(AnalogPin.P2, 99)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 86)
    pins.servoWritePin(AnalogPin.P2, 99)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 85)
    pins.servoWritePin(AnalogPin.P2, 99)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 85)
    pins.servoWritePin(AnalogPin.P2, 99)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 85)
    pins.servoWritePin(AnalogPin.P2, 99)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 85)
    pins.servoWritePin(AnalogPin.P2, 99)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 84)
    pins.servoWritePin(AnalogPin.P2, 98)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 84)
    pins.servoWritePin(AnalogPin.P2, 98)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 84)
    pins.servoWritePin(AnalogPin.P2, 98)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 84)
    pins.servoWritePin(AnalogPin.P2, 98)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 84)
    pins.servoWritePin(AnalogPin.P2, 98)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 83)
    pins.servoWritePin(AnalogPin.P2, 98)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 83)
    pins.servoWritePin(AnalogPin.P2, 98)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 83)
    pins.servoWritePin(AnalogPin.P2, 97)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 83)
    pins.servoWritePin(AnalogPin.P2, 97)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 82)
    pins.servoWritePin(AnalogPin.P2, 97)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 82)
    pins.servoWritePin(AnalogPin.P2, 97)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 82)
    pins.servoWritePin(AnalogPin.P2, 97)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 82)
    pins.servoWritePin(AnalogPin.P2, 97)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 82)
    pins.servoWritePin(AnalogPin.P2, 97)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 81)
    pins.servoWritePin(AnalogPin.P2, 96)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 81)
    pins.servoWritePin(AnalogPin.P2, 96)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 81)
    pins.servoWritePin(AnalogPin.P2, 96)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 81)
    pins.servoWritePin(AnalogPin.P2, 96)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 81)
    pins.servoWritePin(AnalogPin.P2, 96)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 80)
    pins.servoWritePin(AnalogPin.P2, 96)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 80)
    pins.servoWritePin(AnalogPin.P2, 96)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 80)
    pins.servoWritePin(AnalogPin.P2, 95)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 80)
    pins.servoWritePin(AnalogPin.P2, 95)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 80)
    pins.servoWritePin(AnalogPin.P2, 95)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 79)
    pins.servoWritePin(AnalogPin.P2, 95)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 79)
    pins.servoWritePin(AnalogPin.P2, 95)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 79)
    pins.servoWritePin(AnalogPin.P2, 95)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 79)
    pins.servoWritePin(AnalogPin.P2, 94)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 79)
    pins.servoWritePin(AnalogPin.P2, 94)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 79)
    pins.servoWritePin(AnalogPin.P2, 94)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 79)
    pins.servoWritePin(AnalogPin.P2, 94)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 79)
    pins.servoWritePin(AnalogPin.P2, 94)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 79)
    pins.servoWritePin(AnalogPin.P2, 94)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 79)
    pins.servoWritePin(AnalogPin.P2, 94)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 79)
    pins.servoWritePin(AnalogPin.P2, 94)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 80)
    pins.servoWritePin(AnalogPin.P2, 94)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 80)
    pins.servoWritePin(AnalogPin.P2, 94)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 80)
    pins.servoWritePin(AnalogPin.P2, 94)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 80)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 80)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 80)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 80)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 81)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 81)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 81)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 81)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 81)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 81)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 81)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 81)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 82)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 82)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 82)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 82)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 82)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 82)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 82)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 82)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 83)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 83)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 83)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 83)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 83)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 83)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 83)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 84)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 84)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 84)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 84)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 84)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 84)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 85)
    pins.servoWritePin(AnalogPin.P2, 94)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 85)
    pins.servoWritePin(AnalogPin.P2, 94)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P0, 60)
    basic.pause(200)
    pins.servoWritePin(AnalogPin.P1, 85)
    pins.servoWritePin(AnalogPin.P2, 98)
    basic.pause(500)
    pins.servoWritePin(AnalogPin.P0, 80)
    basic.pause(200)
    pins.servoWritePin(AnalogPin.P1, 85)
    pins.servoWritePin(AnalogPin.P2, 98)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 85)
    pins.servoWritePin(AnalogPin.P2, 97)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 85)
    pins.servoWritePin(AnalogPin.P2, 97)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 85)
    pins.servoWritePin(AnalogPin.P2, 97)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 85)
    pins.servoWritePin(AnalogPin.P2, 97)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 85)
    pins.servoWritePin(AnalogPin.P2, 97)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 85)
    pins.servoWritePin(AnalogPin.P2, 96)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 85)
    pins.servoWritePin(AnalogPin.P2, 96)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 85)
    pins.servoWritePin(AnalogPin.P2, 96)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 85)
    pins.servoWritePin(AnalogPin.P2, 96)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 85)
    pins.servoWritePin(AnalogPin.P2, 96)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 85)
    pins.servoWritePin(AnalogPin.P2, 96)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 86)
    pins.servoWritePin(AnalogPin.P2, 96)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 86)
    pins.servoWritePin(AnalogPin.P2, 96)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 86)
    pins.servoWritePin(AnalogPin.P2, 96)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 86)
    pins.servoWritePin(AnalogPin.P2, 96)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 86)
    pins.servoWritePin(AnalogPin.P2, 96)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 86)
    pins.servoWritePin(AnalogPin.P2, 96)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 86)
    pins.servoWritePin(AnalogPin.P2, 96)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 86)
    pins.servoWritePin(AnalogPin.P2, 95)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 86)
    pins.servoWritePin(AnalogPin.P2, 95)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 86)
    pins.servoWritePin(AnalogPin.P2, 95)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 86)
    pins.servoWritePin(AnalogPin.P2, 95)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 86)
    pins.servoWritePin(AnalogPin.P2, 95)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 86)
    pins.servoWritePin(AnalogPin.P2, 95)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 87)
    pins.servoWritePin(AnalogPin.P2, 95)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 87)
    pins.servoWritePin(AnalogPin.P2, 95)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 87)
    pins.servoWritePin(AnalogPin.P2, 95)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 87)
    pins.servoWritePin(AnalogPin.P2, 95)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 87)
    pins.servoWritePin(AnalogPin.P2, 95)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 87)
    pins.servoWritePin(AnalogPin.P2, 95)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 87)
    pins.servoWritePin(AnalogPin.P2, 95)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 87)
    pins.servoWritePin(AnalogPin.P2, 94)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 87)
    pins.servoWritePin(AnalogPin.P2, 94)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 87)
    pins.servoWritePin(AnalogPin.P2, 94)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 87)
    pins.servoWritePin(AnalogPin.P2, 94)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 87)
    pins.servoWritePin(AnalogPin.P2, 94)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 88)
    pins.servoWritePin(AnalogPin.P2, 94)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 88)
    pins.servoWritePin(AnalogPin.P2, 94)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 88)
    pins.servoWritePin(AnalogPin.P2, 95)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 88)
    pins.servoWritePin(AnalogPin.P2, 95)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 89)
    pins.servoWritePin(AnalogPin.P2, 95)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 89)
    pins.servoWritePin(AnalogPin.P2, 95)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 89)
    pins.servoWritePin(AnalogPin.P2, 95)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 89)
    pins.servoWritePin(AnalogPin.P2, 96)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P0, 60)
    basic.pause(200)
}
function drawW() {
    pins.servoWritePin(AnalogPin.P1, 93)
    pins.servoWritePin(AnalogPin.P2, 95)
    basic.pause(500)
    pins.servoWritePin(AnalogPin.P0, 80)
    basic.pause(200)
    pins.servoWritePin(AnalogPin.P1, 93)
    pins.servoWritePin(AnalogPin.P2, 95)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 93)
    pins.servoWritePin(AnalogPin.P2, 95)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 92)
    pins.servoWritePin(AnalogPin.P2, 95)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 92)
    pins.servoWritePin(AnalogPin.P2, 95)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 92)
    pins.servoWritePin(AnalogPin.P2, 94)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 92)
    pins.servoWritePin(AnalogPin.P2, 94)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 93)
    pins.servoWritePin(AnalogPin.P2, 95)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 93)
    pins.servoWritePin(AnalogPin.P2, 95)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 93)
    pins.servoWritePin(AnalogPin.P2, 95)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 93)
    pins.servoWritePin(AnalogPin.P2, 95)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 94)
    pins.servoWritePin(AnalogPin.P2, 95)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 94)
    pins.servoWritePin(AnalogPin.P2, 96)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 94)
    pins.servoWritePin(AnalogPin.P2, 96)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 94)
    pins.servoWritePin(AnalogPin.P2, 96)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 95)
    pins.servoWritePin(AnalogPin.P2, 96)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 95)
    pins.servoWritePin(AnalogPin.P2, 96)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 95)
    pins.servoWritePin(AnalogPin.P2, 96)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 95)
    pins.servoWritePin(AnalogPin.P2, 97)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 95)
    pins.servoWritePin(AnalogPin.P2, 97)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 96)
    pins.servoWritePin(AnalogPin.P2, 97)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 96)
    pins.servoWritePin(AnalogPin.P2, 97)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 96)
    pins.servoWritePin(AnalogPin.P2, 97)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 96)
    pins.servoWritePin(AnalogPin.P2, 98)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 97)
    pins.servoWritePin(AnalogPin.P2, 98)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 97)
    pins.servoWritePin(AnalogPin.P2, 98)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 97)
    pins.servoWritePin(AnalogPin.P2, 98)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 97)
    pins.servoWritePin(AnalogPin.P2, 98)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 97)
    pins.servoWritePin(AnalogPin.P2, 99)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 98)
    pins.servoWritePin(AnalogPin.P2, 99)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 98)
    pins.servoWritePin(AnalogPin.P2, 99)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 98)
    pins.servoWritePin(AnalogPin.P2, 99)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 98)
    pins.servoWritePin(AnalogPin.P2, 99)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 98)
    pins.servoWritePin(AnalogPin.P2, 100)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 99)
    pins.servoWritePin(AnalogPin.P2, 100)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 99)
    pins.servoWritePin(AnalogPin.P2, 100)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 99)
    pins.servoWritePin(AnalogPin.P2, 100)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 99)
    pins.servoWritePin(AnalogPin.P2, 101)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P0, 60)
    basic.pause(200)
    pins.servoWritePin(AnalogPin.P1, 107)
    pins.servoWritePin(AnalogPin.P2, 104)
    basic.pause(500)
    pins.servoWritePin(AnalogPin.P0, 80)
    basic.pause(200)
    pins.servoWritePin(AnalogPin.P1, 107)
    pins.servoWritePin(AnalogPin.P2, 104)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 107)
    pins.servoWritePin(AnalogPin.P2, 104)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 107)
    pins.servoWritePin(AnalogPin.P2, 104)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 107)
    pins.servoWritePin(AnalogPin.P2, 103)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 107)
    pins.servoWritePin(AnalogPin.P2, 103)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 107)
    pins.servoWritePin(AnalogPin.P2, 103)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 106)
    pins.servoWritePin(AnalogPin.P2, 103)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 106)
    pins.servoWritePin(AnalogPin.P2, 102)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 106)
    pins.servoWritePin(AnalogPin.P2, 102)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 106)
    pins.servoWritePin(AnalogPin.P2, 102)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 106)
    pins.servoWritePin(AnalogPin.P2, 102)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 106)
    pins.servoWritePin(AnalogPin.P2, 101)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 105)
    pins.servoWritePin(AnalogPin.P2, 101)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 105)
    pins.servoWritePin(AnalogPin.P2, 101)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 105)
    pins.servoWritePin(AnalogPin.P2, 101)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 105)
    pins.servoWritePin(AnalogPin.P2, 101)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 104)
    pins.servoWritePin(AnalogPin.P2, 100)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 104)
    pins.servoWritePin(AnalogPin.P2, 100)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 104)
    pins.servoWritePin(AnalogPin.P2, 100)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 104)
    pins.servoWritePin(AnalogPin.P2, 100)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 103)
    pins.servoWritePin(AnalogPin.P2, 100)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 103)
    pins.servoWritePin(AnalogPin.P2, 99)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 103)
    pins.servoWritePin(AnalogPin.P2, 99)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 103)
    pins.servoWritePin(AnalogPin.P2, 99)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 102)
    pins.servoWritePin(AnalogPin.P2, 99)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 102)
    pins.servoWritePin(AnalogPin.P2, 98)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 102)
    pins.servoWritePin(AnalogPin.P2, 98)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 102)
    pins.servoWritePin(AnalogPin.P2, 98)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 101)
    pins.servoWritePin(AnalogPin.P2, 98)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 101)
    pins.servoWritePin(AnalogPin.P2, 98)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 101)
    pins.servoWritePin(AnalogPin.P2, 97)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 101)
    pins.servoWritePin(AnalogPin.P2, 97)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 101)
    pins.servoWritePin(AnalogPin.P2, 97)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 100)
    pins.servoWritePin(AnalogPin.P2, 97)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 100)
    pins.servoWritePin(AnalogPin.P2, 97)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 100)
    pins.servoWritePin(AnalogPin.P2, 96)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 100)
    pins.servoWritePin(AnalogPin.P2, 96)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 99)
    pins.servoWritePin(AnalogPin.P2, 96)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 99)
    pins.servoWritePin(AnalogPin.P2, 96)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 99)
    pins.servoWritePin(AnalogPin.P2, 96)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 99)
    pins.servoWritePin(AnalogPin.P2, 95)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 98)
    pins.servoWritePin(AnalogPin.P2, 95)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 98)
    pins.servoWritePin(AnalogPin.P2, 95)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 98)
    pins.servoWritePin(AnalogPin.P2, 95)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 98)
    pins.servoWritePin(AnalogPin.P2, 94)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 97)
    pins.servoWritePin(AnalogPin.P2, 94)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 97)
    pins.servoWritePin(AnalogPin.P2, 94)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 97)
    pins.servoWritePin(AnalogPin.P2, 94)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 97)
    pins.servoWritePin(AnalogPin.P2, 94)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 97)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 96)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 96)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 96)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 96)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 95)
    pins.servoWritePin(AnalogPin.P2, 92)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 95)
    pins.servoWritePin(AnalogPin.P2, 92)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 95)
    pins.servoWritePin(AnalogPin.P2, 92)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 95)
    pins.servoWritePin(AnalogPin.P2, 92)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 94)
    pins.servoWritePin(AnalogPin.P2, 92)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 94)
    pins.servoWritePin(AnalogPin.P2, 91)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 94)
    pins.servoWritePin(AnalogPin.P2, 91)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 94)
    pins.servoWritePin(AnalogPin.P2, 91)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 94)
    pins.servoWritePin(AnalogPin.P2, 91)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 93)
    pins.servoWritePin(AnalogPin.P2, 91)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 93)
    pins.servoWritePin(AnalogPin.P2, 90)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P0, 60)
    basic.pause(200)
    pins.servoWritePin(AnalogPin.P1, 95)
    pins.servoWritePin(AnalogPin.P2, 95)
    basic.pause(500)
    pins.servoWritePin(AnalogPin.P0, 80)
    basic.pause(200)
    pins.servoWritePin(AnalogPin.P1, 95)
    pins.servoWritePin(AnalogPin.P2, 95)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 95)
    pins.servoWritePin(AnalogPin.P2, 94)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 95)
    pins.servoWritePin(AnalogPin.P2, 94)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 95)
    pins.servoWritePin(AnalogPin.P2, 94)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 95)
    pins.servoWritePin(AnalogPin.P2, 94)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 95)
    pins.servoWritePin(AnalogPin.P2, 94)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 95)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 95)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 95)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 95)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 95)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 95)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 95)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 95)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 95)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 95)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 96)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 96)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 96)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 96)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 96)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 96)
    pins.servoWritePin(AnalogPin.P2, 92)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 96)
    pins.servoWritePin(AnalogPin.P2, 92)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 96)
    pins.servoWritePin(AnalogPin.P2, 92)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 96)
    pins.servoWritePin(AnalogPin.P2, 92)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 97)
    pins.servoWritePin(AnalogPin.P2, 92)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 97)
    pins.servoWritePin(AnalogPin.P2, 92)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 97)
    pins.servoWritePin(AnalogPin.P2, 92)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 97)
    pins.servoWritePin(AnalogPin.P2, 92)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 97)
    pins.servoWritePin(AnalogPin.P2, 92)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 97)
    pins.servoWritePin(AnalogPin.P2, 92)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 97)
    pins.servoWritePin(AnalogPin.P2, 92)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 97)
    pins.servoWritePin(AnalogPin.P2, 92)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 97)
    pins.servoWritePin(AnalogPin.P2, 92)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 97)
    pins.servoWritePin(AnalogPin.P2, 92)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 97)
    pins.servoWritePin(AnalogPin.P2, 92)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 97)
    pins.servoWritePin(AnalogPin.P2, 92)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 98)
    pins.servoWritePin(AnalogPin.P2, 92)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 98)
    pins.servoWritePin(AnalogPin.P2, 91)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 98)
    pins.servoWritePin(AnalogPin.P2, 91)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 98)
    pins.servoWritePin(AnalogPin.P2, 91)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 98)
    pins.servoWritePin(AnalogPin.P2, 91)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 98)
    pins.servoWritePin(AnalogPin.P2, 91)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 98)
    pins.servoWritePin(AnalogPin.P2, 91)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 98)
    pins.servoWritePin(AnalogPin.P2, 91)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 98)
    pins.servoWritePin(AnalogPin.P2, 91)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 98)
    pins.servoWritePin(AnalogPin.P2, 91)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 98)
    pins.servoWritePin(AnalogPin.P2, 91)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 98)
    pins.servoWritePin(AnalogPin.P2, 91)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 98)
    pins.servoWritePin(AnalogPin.P2, 91)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 99)
    pins.servoWritePin(AnalogPin.P2, 91)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 99)
    pins.servoWritePin(AnalogPin.P2, 91)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 99)
    pins.servoWritePin(AnalogPin.P2, 91)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 99)
    pins.servoWritePin(AnalogPin.P2, 91)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 99)
    pins.servoWritePin(AnalogPin.P2, 90)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 99)
    pins.servoWritePin(AnalogPin.P2, 90)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 99)
    pins.servoWritePin(AnalogPin.P2, 90)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 99)
    pins.servoWritePin(AnalogPin.P2, 90)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 99)
    pins.servoWritePin(AnalogPin.P2, 90)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 99)
    pins.servoWritePin(AnalogPin.P2, 90)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 99)
    pins.servoWritePin(AnalogPin.P2, 90)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 99)
    pins.servoWritePin(AnalogPin.P2, 90)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 99)
    pins.servoWritePin(AnalogPin.P2, 90)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 100)
    pins.servoWritePin(AnalogPin.P2, 90)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 100)
    pins.servoWritePin(AnalogPin.P2, 90)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 100)
    pins.servoWritePin(AnalogPin.P2, 90)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 100)
    pins.servoWritePin(AnalogPin.P2, 90)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 100)
    pins.servoWritePin(AnalogPin.P2, 90)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 100)
    pins.servoWritePin(AnalogPin.P2, 90)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 100)
    pins.servoWritePin(AnalogPin.P2, 90)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 100)
    pins.servoWritePin(AnalogPin.P2, 90)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 100)
    pins.servoWritePin(AnalogPin.P2, 89)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 100)
    pins.servoWritePin(AnalogPin.P2, 89)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 100)
    pins.servoWritePin(AnalogPin.P2, 89)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 100)
    pins.servoWritePin(AnalogPin.P2, 89)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 101)
    pins.servoWritePin(AnalogPin.P2, 89)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 101)
    pins.servoWritePin(AnalogPin.P2, 89)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 101)
    pins.servoWritePin(AnalogPin.P2, 89)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 101)
    pins.servoWritePin(AnalogPin.P2, 89)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 101)
    pins.servoWritePin(AnalogPin.P2, 89)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 101)
    pins.servoWritePin(AnalogPin.P2, 89)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 101)
    pins.servoWritePin(AnalogPin.P2, 89)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 101)
    pins.servoWritePin(AnalogPin.P2, 89)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 101)
    pins.servoWritePin(AnalogPin.P2, 89)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 101)
    pins.servoWritePin(AnalogPin.P2, 89)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 101)
    pins.servoWritePin(AnalogPin.P2, 89)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 102)
    pins.servoWritePin(AnalogPin.P2, 89)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 102)
    pins.servoWritePin(AnalogPin.P2, 89)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 102)
    pins.servoWritePin(AnalogPin.P2, 89)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 102)
    pins.servoWritePin(AnalogPin.P2, 89)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 102)
    pins.servoWritePin(AnalogPin.P2, 89)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 102)
    pins.servoWritePin(AnalogPin.P2, 90)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 102)
    pins.servoWritePin(AnalogPin.P2, 90)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 102)
    pins.servoWritePin(AnalogPin.P2, 90)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 102)
    pins.servoWritePin(AnalogPin.P2, 90)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 102)
    pins.servoWritePin(AnalogPin.P2, 90)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 102)
    pins.servoWritePin(AnalogPin.P2, 90)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P0, 60)
    basic.pause(200)
    pins.servoWritePin(AnalogPin.P1, 96)
    pins.servoWritePin(AnalogPin.P2, 92)
    basic.pause(500)
    pins.servoWritePin(AnalogPin.P0, 80)
    basic.pause(200)
    pins.servoWritePin(AnalogPin.P1, 96)
    pins.servoWritePin(AnalogPin.P2, 92)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 97)
    pins.servoWritePin(AnalogPin.P2, 92)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 97)
    pins.servoWritePin(AnalogPin.P2, 92)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 97)
    pins.servoWritePin(AnalogPin.P2, 92)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 97)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 97)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 98)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 98)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 98)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 98)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 98)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 99)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 99)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 99)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 99)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 99)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 100)
    pins.servoWritePin(AnalogPin.P2, 93)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 100)
    pins.servoWritePin(AnalogPin.P2, 94)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 100)
    pins.servoWritePin(AnalogPin.P2, 94)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 100)
    pins.servoWritePin(AnalogPin.P2, 94)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 101)
    pins.servoWritePin(AnalogPin.P2, 94)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 101)
    pins.servoWritePin(AnalogPin.P2, 94)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 101)
    pins.servoWritePin(AnalogPin.P2, 94)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 101)
    pins.servoWritePin(AnalogPin.P2, 95)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 102)
    pins.servoWritePin(AnalogPin.P2, 95)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 102)
    pins.servoWritePin(AnalogPin.P2, 95)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 102)
    pins.servoWritePin(AnalogPin.P2, 95)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 103)
    pins.servoWritePin(AnalogPin.P2, 95)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 103)
    pins.servoWritePin(AnalogPin.P2, 96)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 103)
    pins.servoWritePin(AnalogPin.P2, 96)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 104)
    pins.servoWritePin(AnalogPin.P2, 96)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 104)
    pins.servoWritePin(AnalogPin.P2, 96)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 104)
    pins.servoWritePin(AnalogPin.P2, 96)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 104)
    pins.servoWritePin(AnalogPin.P2, 97)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 105)
    pins.servoWritePin(AnalogPin.P2, 97)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 105)
    pins.servoWritePin(AnalogPin.P2, 97)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 105)
    pins.servoWritePin(AnalogPin.P2, 97)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 106)
    pins.servoWritePin(AnalogPin.P2, 97)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 106)
    pins.servoWritePin(AnalogPin.P2, 98)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 106)
    pins.servoWritePin(AnalogPin.P2, 98)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 106)
    pins.servoWritePin(AnalogPin.P2, 98)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P0, 60)
    basic.pause(200)
    pins.servoWritePin(AnalogPin.P1, 97)
    pins.servoWritePin(AnalogPin.P2, 92)
    basic.pause(500)
    pins.servoWritePin(AnalogPin.P0, 80)
    basic.pause(200)
    pins.servoWritePin(AnalogPin.P1, 97)
    pins.servoWritePin(AnalogPin.P2, 92)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 97)
    pins.servoWritePin(AnalogPin.P2, 92)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 97)
    pins.servoWritePin(AnalogPin.P2, 91)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 97)
    pins.servoWritePin(AnalogPin.P2, 91)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 97)
    pins.servoWritePin(AnalogPin.P2, 91)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 96)
    pins.servoWritePin(AnalogPin.P2, 90)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 96)
    pins.servoWritePin(AnalogPin.P2, 90)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 96)
    pins.servoWritePin(AnalogPin.P2, 90)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 96)
    pins.servoWritePin(AnalogPin.P2, 89)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 96)
    pins.servoWritePin(AnalogPin.P2, 89)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 96)
    pins.servoWritePin(AnalogPin.P2, 89)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 96)
    pins.servoWritePin(AnalogPin.P2, 89)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 96)
    pins.servoWritePin(AnalogPin.P2, 89)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P0, 60)
    basic.pause(200)
}
function drawA() {
    pins.servoWritePin(AnalogPin.P1, 92)
    pins.servoWritePin(AnalogPin.P2, 88)
    basic.pause(500)
    pins.servoWritePin(AnalogPin.P0, 80)
    basic.pause(200)
    pins.servoWritePin(AnalogPin.P1, 92)
    pins.servoWritePin(AnalogPin.P2, 88)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 92)
    pins.servoWritePin(AnalogPin.P2, 88)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 92)
    pins.servoWritePin(AnalogPin.P2, 87)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 92)
    pins.servoWritePin(AnalogPin.P2, 87)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 92)
    pins.servoWritePin(AnalogPin.P2, 87)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 91)
    pins.servoWritePin(AnalogPin.P2, 86)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 91)
    pins.servoWritePin(AnalogPin.P2, 86)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 91)
    pins.servoWritePin(AnalogPin.P2, 86)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 91)
    pins.servoWritePin(AnalogPin.P2, 85)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 91)
    pins.servoWritePin(AnalogPin.P2, 85)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 91)
    pins.servoWritePin(AnalogPin.P2, 85)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 91)
    pins.servoWritePin(AnalogPin.P2, 85)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 91)
    pins.servoWritePin(AnalogPin.P2, 85)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 91)
    pins.servoWritePin(AnalogPin.P2, 85)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 91)
    pins.servoWritePin(AnalogPin.P2, 84)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 91)
    pins.servoWritePin(AnalogPin.P2, 84)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 91)
    pins.servoWritePin(AnalogPin.P2, 84)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 91)
    pins.servoWritePin(AnalogPin.P2, 84)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 91)
    pins.servoWritePin(AnalogPin.P2, 84)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 91)
    pins.servoWritePin(AnalogPin.P2, 84)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 91)
    pins.servoWritePin(AnalogPin.P2, 84)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 91)
    pins.servoWritePin(AnalogPin.P2, 84)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 91)
    pins.servoWritePin(AnalogPin.P2, 84)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 91)
    pins.servoWritePin(AnalogPin.P2, 83)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 91)
    pins.servoWritePin(AnalogPin.P2, 83)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 91)
    pins.servoWritePin(AnalogPin.P2, 83)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 91)
    pins.servoWritePin(AnalogPin.P2, 83)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 91)
    pins.servoWritePin(AnalogPin.P2, 83)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 91)
    pins.servoWritePin(AnalogPin.P2, 83)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 91)
    pins.servoWritePin(AnalogPin.P2, 83)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 91)
    pins.servoWritePin(AnalogPin.P2, 83)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 92)
    pins.servoWritePin(AnalogPin.P2, 83)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 92)
    pins.servoWritePin(AnalogPin.P2, 83)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 92)
    pins.servoWritePin(AnalogPin.P2, 83)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 92)
    pins.servoWritePin(AnalogPin.P2, 83)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 92)
    pins.servoWritePin(AnalogPin.P2, 83)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 92)
    pins.servoWritePin(AnalogPin.P2, 82)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 92)
    pins.servoWritePin(AnalogPin.P2, 82)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 92)
    pins.servoWritePin(AnalogPin.P2, 82)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 92)
    pins.servoWritePin(AnalogPin.P2, 82)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 92)
    pins.servoWritePin(AnalogPin.P2, 82)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P0, 60)
    basic.pause(200)
    pins.servoWritePin(AnalogPin.P1, 88)
    pins.servoWritePin(AnalogPin.P2, 85)
    basic.pause(500)
    pins.servoWritePin(AnalogPin.P0, 80)
    basic.pause(200)
    pins.servoWritePin(AnalogPin.P1, 88)
    pins.servoWritePin(AnalogPin.P2, 85)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 88)
    pins.servoWritePin(AnalogPin.P2, 84)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 88)
    pins.servoWritePin(AnalogPin.P2, 84)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 88)
    pins.servoWritePin(AnalogPin.P2, 84)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 88)
    pins.servoWritePin(AnalogPin.P2, 84)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 87)
    pins.servoWritePin(AnalogPin.P2, 83)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 87)
    pins.servoWritePin(AnalogPin.P2, 83)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 87)
    pins.servoWritePin(AnalogPin.P2, 83)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 87)
    pins.servoWritePin(AnalogPin.P2, 83)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 86)
    pins.servoWritePin(AnalogPin.P2, 83)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 86)
    pins.servoWritePin(AnalogPin.P2, 83)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 86)
    pins.servoWritePin(AnalogPin.P2, 82)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 86)
    pins.servoWritePin(AnalogPin.P2, 82)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 85)
    pins.servoWritePin(AnalogPin.P2, 82)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 85)
    pins.servoWritePin(AnalogPin.P2, 82)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 85)
    pins.servoWritePin(AnalogPin.P2, 82)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 85)
    pins.servoWritePin(AnalogPin.P2, 82)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 84)
    pins.servoWritePin(AnalogPin.P2, 81)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 84)
    pins.servoWritePin(AnalogPin.P2, 81)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 84)
    pins.servoWritePin(AnalogPin.P2, 81)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 84)
    pins.servoWritePin(AnalogPin.P2, 81)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 83)
    pins.servoWritePin(AnalogPin.P2, 81)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 83)
    pins.servoWritePin(AnalogPin.P2, 80)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 83)
    pins.servoWritePin(AnalogPin.P2, 80)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 83)
    pins.servoWritePin(AnalogPin.P2, 80)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 82)
    pins.servoWritePin(AnalogPin.P2, 80)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 82)
    pins.servoWritePin(AnalogPin.P2, 80)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 82)
    pins.servoWritePin(AnalogPin.P2, 80)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 82)
    pins.servoWritePin(AnalogPin.P2, 79)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 81)
    pins.servoWritePin(AnalogPin.P2, 79)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 81)
    pins.servoWritePin(AnalogPin.P2, 79)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 81)
    pins.servoWritePin(AnalogPin.P2, 79)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 81)
    pins.servoWritePin(AnalogPin.P2, 79)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 80)
    pins.servoWritePin(AnalogPin.P2, 79)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 80)
    pins.servoWritePin(AnalogPin.P2, 79)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 80)
    pins.servoWritePin(AnalogPin.P2, 78)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 80)
    pins.servoWritePin(AnalogPin.P2, 78)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 80)
    pins.servoWritePin(AnalogPin.P2, 78)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 80)
    pins.servoWritePin(AnalogPin.P2, 78)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 80)
    pins.servoWritePin(AnalogPin.P2, 78)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 80)
    pins.servoWritePin(AnalogPin.P2, 78)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 80)
    pins.servoWritePin(AnalogPin.P2, 78)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 80)
    pins.servoWritePin(AnalogPin.P2, 77)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 80)
    pins.servoWritePin(AnalogPin.P2, 77)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 80)
    pins.servoWritePin(AnalogPin.P2, 77)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 80)
    pins.servoWritePin(AnalogPin.P2, 77)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 80)
    pins.servoWritePin(AnalogPin.P2, 77)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 80)
    pins.servoWritePin(AnalogPin.P2, 77)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 81)
    pins.servoWritePin(AnalogPin.P2, 77)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 81)
    pins.servoWritePin(AnalogPin.P2, 77)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 81)
    pins.servoWritePin(AnalogPin.P2, 77)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 81)
    pins.servoWritePin(AnalogPin.P2, 77)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 81)
    pins.servoWritePin(AnalogPin.P2, 77)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 81)
    pins.servoWritePin(AnalogPin.P2, 77)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 81)
    pins.servoWritePin(AnalogPin.P2, 77)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 81)
    pins.servoWritePin(AnalogPin.P2, 76)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 81)
    pins.servoWritePin(AnalogPin.P2, 76)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 81)
    pins.servoWritePin(AnalogPin.P2, 76)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 81)
    pins.servoWritePin(AnalogPin.P2, 76)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 81)
    pins.servoWritePin(AnalogPin.P2, 76)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 81)
    pins.servoWritePin(AnalogPin.P2, 76)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 81)
    pins.servoWritePin(AnalogPin.P2, 76)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 82)
    pins.servoWritePin(AnalogPin.P2, 76)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 82)
    pins.servoWritePin(AnalogPin.P2, 76)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 82)
    pins.servoWritePin(AnalogPin.P2, 76)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 82)
    pins.servoWritePin(AnalogPin.P2, 76)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 82)
    pins.servoWritePin(AnalogPin.P2, 76)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 82)
    pins.servoWritePin(AnalogPin.P2, 76)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 82)
    pins.servoWritePin(AnalogPin.P2, 76)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 82)
    pins.servoWritePin(AnalogPin.P2, 76)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 82)
    pins.servoWritePin(AnalogPin.P2, 76)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 82)
    pins.servoWritePin(AnalogPin.P2, 76)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 82)
    pins.servoWritePin(AnalogPin.P2, 76)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 82)
    pins.servoWritePin(AnalogPin.P2, 76)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 82)
    pins.servoWritePin(AnalogPin.P2, 76)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 82)
    pins.servoWritePin(AnalogPin.P2, 75)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 82)
    pins.servoWritePin(AnalogPin.P2, 75)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 83)
    pins.servoWritePin(AnalogPin.P2, 75)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 83)
    pins.servoWritePin(AnalogPin.P2, 75)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 83)
    pins.servoWritePin(AnalogPin.P2, 75)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 83)
    pins.servoWritePin(AnalogPin.P2, 75)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P0, 60)
    basic.pause(200)
    pins.servoWritePin(AnalogPin.P1, 91)
    pins.servoWritePin(AnalogPin.P2, 82)
    basic.pause(500)
    pins.servoWritePin(AnalogPin.P0, 80)
    basic.pause(200)
    pins.servoWritePin(AnalogPin.P1, 91)
    pins.servoWritePin(AnalogPin.P2, 82)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 90)
    pins.servoWritePin(AnalogPin.P2, 82)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 90)
    pins.servoWritePin(AnalogPin.P2, 81)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 90)
    pins.servoWritePin(AnalogPin.P2, 81)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 90)
    pins.servoWritePin(AnalogPin.P2, 81)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 89)
    pins.servoWritePin(AnalogPin.P2, 81)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 89)
    pins.servoWritePin(AnalogPin.P2, 81)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 89)
    pins.servoWritePin(AnalogPin.P2, 80)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 89)
    pins.servoWritePin(AnalogPin.P2, 80)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 88)
    pins.servoWritePin(AnalogPin.P2, 80)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 88)
    pins.servoWritePin(AnalogPin.P2, 80)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 88)
    pins.servoWritePin(AnalogPin.P2, 80)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 88)
    pins.servoWritePin(AnalogPin.P2, 79)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 87)
    pins.servoWritePin(AnalogPin.P2, 79)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 87)
    pins.servoWritePin(AnalogPin.P2, 79)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 87)
    pins.servoWritePin(AnalogPin.P2, 79)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 87)
    pins.servoWritePin(AnalogPin.P2, 79)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 86)
    pins.servoWritePin(AnalogPin.P2, 78)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 86)
    pins.servoWritePin(AnalogPin.P2, 78)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 86)
    pins.servoWritePin(AnalogPin.P2, 78)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 86)
    pins.servoWritePin(AnalogPin.P2, 78)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 85)
    pins.servoWritePin(AnalogPin.P2, 77)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 85)
    pins.servoWritePin(AnalogPin.P2, 77)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 85)
    pins.servoWritePin(AnalogPin.P2, 77)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 85)
    pins.servoWritePin(AnalogPin.P2, 77)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 84)
    pins.servoWritePin(AnalogPin.P2, 77)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 84)
    pins.servoWritePin(AnalogPin.P2, 77)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 84)
    pins.servoWritePin(AnalogPin.P2, 76)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 84)
    pins.servoWritePin(AnalogPin.P2, 76)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 83)
    pins.servoWritePin(AnalogPin.P2, 76)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 83)
    pins.servoWritePin(AnalogPin.P2, 76)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 83)
    pins.servoWritePin(AnalogPin.P2, 76)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P1, 82)
    pins.servoWritePin(AnalogPin.P2, 75)
    basic.pause(10)
    pins.servoWritePin(AnalogPin.P0, 60)
    basic.pause(200)
}
basic.forever(function () {
    basic.showIcon(IconNames.Heart)
    homePosition()
    drawR()
    basic.showLeds(`
        . # . . .
        . # . . .
        . # . . #
        . # . # .
        . # # . .
        `)
    drawE()
    basic.showLeds(`
        . . . # .
        . . # . .
        . # # . .
        # . # . .
        . . # . .
        `)
    drawW()
    basic.showLeds(`
        # # # # #
        # . . . #
        . . . . #
        . . . # .
        . # # . .
        `)
    drawA()
    basic.showIcon(IconNames.Happy)
    homePosition()
    basic.pause(2000)
    clearBoard()
})